---
title: 'ReadMe: Analysis for Economic Benefits of Recreation in Canada (Lloyd-Smith,
  CJE)'
author: "Pat Lloyd-Smith"
date: "November 2020"
output:
  pdf_document: default
  html_document: default
---

Overview
--------

The code in this replication package uses R to construct all analyses in *Economic Benefits of Recreation in Canada*. The data is from the Canadian Nature Survey (2012). Additional information on the dataset is provided in Federal, Provincial, and Territorial Governments of Canada (2014). Two master files run all of the code to generate the data for the 4 figures and 7 tables in the paper. The replicator should expect the code to run for about 48 hours. All scripts are available at https://github.com/plloydsmith/RecBenefitsCanadaCJE

Data Availability and Provenance Statements
----------------------------

- [ ] This paper does not involve analysis of external data (i.e., no data are used or the only data are generated by the authors via simulation in their code).

### Statement about Rights

- [x] I certify that the author(s) of the manuscript have legitimate access to and permission to use the data used in this manuscript. 


### License for Data

Licence: Open Government Licence - Canada

### Summary of Availability

- [x] All data **are** publicly available.
- [ ] Some data **cannot be made** publicly available.
- [ ] **No data can be made** publicly available.

### Details on each Data Source

Data on Canadian recreation behaviour were downloaded from the Government of Canada's Open Data portal. Data can be downloaded from https://open.canada.ca/data/en/dataset/694b9da8-1f06-4ebe-ad38-1b14bdaf756e, under the Resource Name "cns2012pumf.xlsx" and Resource Type Dataset. The data dictionary is also provided at this link. A copy of the data is provided as part of this archive. The data are in the public domain.

Datafile:  `Raw2012Data.csv`

Computational requirements
---------------------------

### Software Requirements

- R 3.6.3
  - `pacman`
  - `tidyverse`
  - `mice`
  - `fastDummies`
  - `furrr`
  - `micemd`
  - `randtoolbox`
  - `rstan`
  - `rmdcev`

### Memory and Runtime Requirements

#### Summary

Approximate time needed to reproduce the analyses on a standard (CURRENT YEAR) desktop machine:

- [ ] <10 minutes
- [ ] 10-60 minutes
- [ ] 1-8 hours
- [ ] 8-24 hours
- [x] 1-3 days
- [ ] 3-14 days
- [ ] > 14 days
- [ ] Not feasible to run on a desktop machine, as described below.

#### Details

The code was run on a **7-core Intel-based desktop with 32 GB of RAM and a Windows 10 operating system**. 

Description of programs/code
----------------------------

All scripts are available at https://github.com/plloydsmith/RecBenefitsCanadaCJE.
The code is licensed under a MIT/BSD/GPL/Creative Commons license.

Instructions to Replicators
---------------------------

- You will need to install the following R packages

`install.packages("pacman", "tidyverse", "mice", "fastDummies", "furrr", "micemd", "randtoolbox", "rstan", "rmdcev")`

- Download the data file referenced above. Save the `cns2012pumf.xlsx` file as `Raw2012Data.csv` in the `data/raw` folder
- Run the `1PrepareData.R` script. Note that this script involves intensive data imputation and takes a long time to run on a desktop computer (~48 hours on a desktop computer with 32 GB RAM).
- Run the `2RunAnalysis` R script to generate all figures and tables in the paper.

List of tables and programs
---------------------------

The provided code reproduces:

- [ ] All numbers provided in text in the paper
- [x] All tables and figures in the paper
- [ ] Selected tables and figures in the paper, as explained and justified below.


| Figure/Table  | Program             | Line Number | Output file                      | Note   |
|-----------|-------------------------|-------------|----------------------------------|-------|
| Table 1 | CreateWelfareTables.R | 58            | activity_table.tex   ||
| Table 2 | CreateEstimationTables.R | 55          | mdcev_national_w.tex   ||
| Table 3 | CreateWelfareTables.R| 138         | welfare_national_w_combined.tex   ||
| Table 4 | CreateWelfareTables.R| 209         | welfare_provincial_combined.tex    ||
| Table B-1 | CreateAppendixTables.R | 79         | days_prov.tex                      ||
| Table B-2 | CreateAppendixTables.R | 128         | costs_prov.tex                      ||
| Table B-3 | CreateEstimationTables.R| 103         | mdcev_prov1.tex, mdcev_prov2.tex, mdcev_prov3.tex                      ||
| Figure 1 | CreateAppendixTables.R |   47          |  multiple_activities.png |          |
| Figure 2 | CreateWelfareTables.R      | 242            | wtp_day.png                      ||
| Figure A-1 | from survey |             |            |       |
| Figure A-2 | from survey |             |             |     |

## References

Federal, Provincial, and Territorial Governments of Canada (2014), 2012 Canadian Nature
Survey: Awareness, participation, and expenditures in nature-based recreation, conservation, and subsistence activities, Technical report, Canadian Councils of Resource Ministers,
Ottawa, ON.

Canadian Nature Survey, 2012. "Canadian Nature Survey [dataset]" *Environment and Climate Change Canada*. Accessed January 21, 2017.

---

